# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8baf5ffc481ddd8861ab1e16897a17fc9677d3a7be08f17764912d1365c599acc59fed7f8ade6aacb8fbfaeebb8a2c7210c65104bc3db4aa6e35d198d8c61e

test:
  secret_key_base: 34c1b913cce7af6691be4cc189293d2db388e1a675c512f81b22956a353ff6361c8416f927e6e9623cc73d063ead2d56475504c0600046066e667d678eae8afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
